spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-service:5432/postgres
    username: postgres
    password: skillbox
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:changelog_init.xml
    enabled: true
    drop-first: true

vars:
  captchaCharStr: 0123456789

endpoints:
  admin: "/api/v1/admin/**"
  public: "/api/v1/auth/**"
roles:
  admin: "admin"
jwt:
  token:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970