spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST:jdbc:postgresql://postgres-service:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:skillbox}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:changelog_init.xml
    enabled: true
    drop-first: false
  servlet:
    multipart:
      max-file-size: 10MB
  kafka:
    bootstrap-servers: ${BOOTSTRAP-SERVERS:kafka-service:9092}
    consumer:
      group-id: ${GROUP-ID:group-1}
  mail:
    host: ${MAIL_HOST:smtp.yandex.ru}
    port: 465
    username: ${MAIL_USERNAME:javapro42@yandex.ru}
    password: ${MAIL_PASSWORD:mjysuhedahhswnef}

vars:
  captchaCharStr: 0123456789
host:
  local: ${PROD_HOST:http://212.22.70.159:1111}

endpoints:
  admin:
    /api/v1/admin/**,
    /admin/**,
    /api/v1/admin-console/**
  public:
   /api/v1/auth/**,
   /swagger-ui/**,
   /api-docs/**,
   /api-docs.yaml,
   /actuator/**,
   /metrics**

roles:
  admin: "admin"
jwt:
  token:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

vk_data:
  token: vk1.a.-sCwwHZ-dCzuLf9UOHiiwRxHtVW8BUg-XcX0reW-P6nY5tG9l-qDUqE4ADOmE1GOBTQTSAauxK5xuxcVYPLbihmO81gmqotg2_mpaa8RNWkfbN2OJOdYUxfk8-mbyKS31K3Ml69kbBevq_VHzWBEiRAlcOWIuSWG07F0xqdvAP1MmDbUPB7WqhGEvDknJM_37eg13qmrDZi3JKR5jMer3Q
  app_id: 51762981
  country_code_list: RU,BY,KZ,AM

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"
    operationsSorter: method

cloudinary:
  cloud_name: dmcmd4g2s
  api_key: 358825755328599
  api_secret: NoYeSddTS8z06a5Dga_wQZO6RZU

logging:
  level:
    org:
      apache:
        kafka: ${KAFKA_LOGGER:OFF}
    root: ${ROOT_LOGGER:info}
    ru:
      skillbox:
        diplom:
          group42: ${PROJECT_LOGGER:debug}

kafka-enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true